#!/bin/bash
DIRNAME=$0
if [ "${DIRNAME:0:1}" = "/" ];then
    CURDIR=`dirname $DIRNAME`
else
    CURDIR="`pwd`"/"`dirname $DIRNAME`"
fi
li=(01)
for param in $@
do
if [[ $param == -f ]]
then
li=(01 02 03 04 05 06 07 08 09 10 11)
fi
done
for param in $@
do
if [[ $param =~ \.fa[a-z]*$ ]]
then
for i in ${li[@]};do $CURDIR/gfClient localhost 40$i $CURDIR/database/ $param $CURDIR/output$i.psl > /dev/null; done
$CURDIR/pslCat $CURDIR/output*.psl -nohead |sort  -k 1nr -k 5n -k 7n -k 2n|head -100 |cut -f 1,2,5,6,7,8,9,10,12,13,14,16,17
rm $CURDIR/output*.psl
fi
done
