#!/bin/bash
li=(01)
for param in $@
do
if [[ $param == -f ]] 
then
li=(01 02 03 04 05 06 07 08 09 10 11)
fi
done
for param in $@
do 
if [[ $param =~ \.fa[a-z]*$ ]]
then
for i in ${li[@]};do /share/www/PPanG/blat/gfClient localhost 40$i /share/www/PPanG/blat/ $param output$i.psl > /dev/null; done
 /share/www/PPanG/blat/pslCat output*.psl -nohead |sort  -k 1nr -k 5n -k 7n -k 2n|head -200 |cut -f 1,2,5,6,7,8,9,10,12,13,14,16,17
rm output*.psl
fi
done
